name: Release

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case:
          - { version: "latest" }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test feature installation
        run: |
          mkdir -p /tmp/test
          cd /tmp/test
          
          # Create test devcontainer
          cat > devcontainer.json << EOF
          {
            "image": "ubuntu:22.04",
            "features": {
              "../": {
                "version": "${{ matrix.test-case.version }}"
              }
            }
          }
          EOF
          
          # Test the feature
          docker run --rm -v "$GITHUB_WORKSPACE:/workspace" -v "/tmp/test:/test" \
            ubuntu:22.04 bash -c "
              cd /workspace/src/graphviz && chmod +x install.sh && 
              VERSION=${{ matrix.test-case.version }} ./install.sh
            "

  publish:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}